name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Download dependencies
        run: go install

      - name: Run unit tests
        run: make test

      - name: Build and compress binaries into zip
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o secfetch .
          zip secfetch-${{ matrix.goos }}-${{ matrix.goarch }}.zip secfetch

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: secfetch-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          path: secfetch-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          name: secfetch-${{ matrix.goos }}-${{ matrix.goarch }}.zip

      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./secfetch-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          asset_name: secfetch-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          asset_content_type: application/zip
